version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - geeks
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
      - ./src/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - geeks
  mysql:
    image: mysql/mysql-server:8.0
    env_file:
      - ./env/mysql.env
    networks:
      - geeks
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}" ]
      retries: 3
      timeout: 5s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - 81:80
    networks:
      - geeks

networks:
  geeks:
    driver: bridge